include(cmake/download-cpm.cmake)

# extra options must stay in comments otherwise it's ignored (idk why)

set(CPM_USE_NAMED_CACHE_DIRECTORIES ON)

cpmaddpackage("gh:libsdl-org/SDL#release-2.30.1")

cpmaddpackage(
	NAME
	glew
	GIT_TAG
	glew-cmake-2.2.0
	GITHUB_REPOSITORY
	Perlmint/glew-cmake
	OPTIONS
	"ONLY_LIBS ON"
	"glew-cmake_BUILD_SHARED FALSE"
	EXCLUDE_FROM_ALL
	SYSTEM
)

cpmaddpackage(
	NAME glm
	GIT_TAG	1.0.1
	GITHUB_REPOSITORY "g-truc/glm"
	OPTIONS
	"BUILD_SHARED_LIBS OFF"
	EXCLUDE_FROM_ALL
	SYSTEM
)

cpmaddpackage(
	NAME
	Assimp
	VERSION
	5.4.0
	GITHUB_REPOSITORY
	assimp/assimp
	OPTIONS
	"BUILD_SHARED_LIBS OFF"
	"ASSIMP_WARNINGS_AS_ERRORS OFF"
	"ASSIMP_NO_EXPORT ON"
	"ASSIMP_BUILD_TESTS OFF"
	"USE_STATIC_CRT ON"
	"ASSIMP_INSTALL OFF"
	"ASSIMP_BUILD_ALL_EXPORTERS_BY_DEFAULT OFF"
	"ASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT OFF"
	"ASSIMP_BUILD_GLTF_IMPORTER ON"
	EXCLUDE_FROM_ALL
	SYSTEM
)

cpmaddpackage(
	NAME
	GSL
	VERSION
	4.0.0
	GITHUB_REPOSITORY
	microsoft/GSL
	OPTIONS
	"BUILD_SHARED_LIBS OFF"
	EXCLUDE_FROM_ALL
	SYSTEM
)

set(ABSL_PROPAGATE_CXX_STD ON)
set(ABSL_USE_SYSTEM_INCLUDES ON)
cpmaddpackage(
	NAME
	abseil
	GIT_TAG
	20240116.1
	GITHUB_REPOSITORY
	abseil/abseil-cpp
	OPTIONS
	"BUILD_SHARED_LIBS OFF"
	"ABSL_PROPAGATE_CXX_STD ON"
	"ABSL_USE_SYSTEM_INCLUDES ON"
	EXCLUDE_FROM_ALL
	SYSTEM
)

cpmaddpackage(
	NAME
	spdlog
	VERSION
	1.13.0
	GITHUB_REPOSITORY
	gabime/spdlog
	OPTIONS
	"BUILD_SHARED_LIBS OFF"
	"SPDLOG_FMT_EXTERNAL OFF"
	EXCLUDE_FROM_ALL
	SYSTEM
)

cpmaddpackage(
	NAME
	KTX-Software
	VERSION
	4.3.2
	GITHUB_REPOSITORY
	KhronosGroup/KTX-Software
	OPTIONS
	"BUILD_SHARED_LIBS OFF"
	"KTX_FEATURE_STATIC_LIBRARY ON"
	"KTX_FEATURE_TOOLS OFF"
	"KTX_FEATURE_TESTS OFF"
	"KTX_FEATURE_KTX1 ON"
	"KTX_FEATURE_VK_UPLOAD OFF"
	"KTX_INSTALL_TARGETS OFF"
	EXCLUDE_FROM_ALL
	SYSTEM
)

add_subdirectory(./external)
